#!/usr/bin/env bash

if [ ! -z "$1" ] && [[ "$1" == "clean" ]]; then
	rm -rf site
	exit 0
fi

mkdir -p site/posts
while read line; do
	TITLE=$(echo "$line" | cut -f1)
	FILENAME=$(echo "$line" | cut -f2)
	scripts/format-blogpost.js "${TITLE}" posts/${FILENAME}.md > site/posts/${FILENAME}.html
done < post_list

cp -r post_files/* site/posts/
for folder in $(find posts -mindepth 1 -maxdepth 1 -type d) ; do \
	cp -r "$folder" "site/$folder" ; \
done

cp -r index_files/* site/
scripts/format-index > site/index.html
