#!/usr/bin/env bash

set -e

rm -rf site
mkdir -p site/posts
while read line; do
	TITLE=$(echo "$line" | cut -f1)
	FILENAME=$(echo "$line" | cut -f2)
	DESCRIPTION=$(echo "$line" | cut -f3)
	scripts/format-blogpost.js "${TITLE}" posts/${FILENAME}.md "$DESCRIPTION" > site/posts/${FILENAME}.html
done < posts/post_list

cp -r post_files/* site/posts/
for folder in $(find posts -mindepth 1 -maxdepth 1 -type d) ; do \
	cp -r "$folder" "site/$folder" ; \
done

cp -r index_files/* site/
scripts/format-index $1 > site/index.html
